name: Container

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      tag:
        type: string
        required: false
      containers:
        type: string
        required: true

jobs:
  container:
    if: ${{ inputs.tag }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        container: ${{ fromJSON(inputs.containers) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate
        run: |
          python3 -mpip install pygithub ruamel.yaml
          ./generate.py container '${{ inputs.project }}' '${{ inputs.tag }}' '${{ matrix.container }}'

      - name: Build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: sshfs
          copyback: false

          prepare: |
            sysctl net.inet.ip.forwarding=1

            mkdir -p /usr/local/etc/pkg/repos
            echo 'FreeBSD: { url: "pkg+https://pkg.freebsd.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            pkg install -y podman-suite

            truncate -s 32G /var/tmp/z
            mkdir -p /var/db/containers/storage
            zpool create -R /var/db/containers/storage -O mountpoint=/ -O compression=lz4 z /var/tmp/z

            buildah login -u ${{ github.actor }} -p ${{ github.token }} ghcr.io

          run: |
            ./build.sh

      - name: Cleanup
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: ${{ matrix.container }}
          keep-n-tagged: 3
          exclude-tags: latest
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
