name: Dispatch

on:
  workflow_dispatch:
    inputs:
      cloudflared:
        type: string
        required: false
      grafana:
        type: string
        required: false
      step-posture-connector:
        type: string
        required: false
      sing-box:
        type: string
        required: false
      victoria-logs:
        type: string
        required: false
      victoria-metrics:
        type: string
        required: false

permissions:
  contents: write
  packages: write

jobs:
  dispatch:
    strategy:
      matrix:
        include:
          - project: cloudflared
            repo: cloudflare/cloudflared
            cgo: false
            packages: '["cloudflared"]'
            containers: '["cloudflared"]'
          - project: grafana
            repo: grafana/grafana
            cgo: true
            packages: '["grafana"]'
            containers: '["grafana"]'
          - project: step-posture-connector
            repo: jedda/step-posture-connector
            cgo: false
            packages: '["step-posture-connector"]'
            containers: '["step-posture-connector"]'
          - project: sing-box
            repo: sagernet/sing-box
            cgo: false
            packages: '["sing-box"]'
            containers: '["sing-box"]'
          - project: victoria-logs
            repo: VictoriaMetrics/VictoriaMetrics
            cgo: false
            packages: '["victoria-logs"]'
            containers: '["victoria-logs"]'
          - project: victoria-metrics
            repo: VictoriaMetrics/VictoriaMetrics
            cgo: false
            packages: '["victoria-metrics", "vmutils"]'
            containers: '["victoria-metrics"]'
    name: ${{ matrix.project }}
    uses: ./.github/workflows/build.yaml
    with:
      project: ${{ matrix.project }}
      tag: ${{ inputs[matrix.project] }}
      repo: ${{ matrix.repo }}
      cgo: ${{ matrix.cgo }}
      packages: ${{ matrix.packages }}
      containers: ${{ matrix.containers }}
